apiVersion: v1
kind: Pod
metadata:
  name: multitool
  labels:
    app: multitool

spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    env:
      - name: HTTP_PORT
        value: "1080"
      - name: HTTPS_PORT
        value: "10443"
