apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  ports:
  - name: nginx
    port: 9001
    targetPort: 80
  - name: multitoolhttp
    port: 9002
    targetPort: 8080

  selector:
    app: deployment1
